Origen = 
Sql.Database("13.68.80.134", "IscalaDB", 
[Query=
"WITH SKU_Correctos AS (#(lf)    SELECT #(lf)        
'API3' AS codigo_producto, 'Apiret Sol Oral 120mL' AS producto#(lf)    UNION ALL#(lf)    SELECT #(lf)        
'CLA7' AS codigo_producto, 'Clarix Sol Nasal 15mL' AS producto#(lf)    UNION ALL#(lf)    SELECT #(lf)        
'CLA6' AS codigo_producto, 'Clarix Sol Nasal Ped 15mL' AS producto#(lf)    UNION ALL#(lf)    SELECT #(lf)        
'CLA9' AS codigo_producto, 'Clarix Solución Oft. BFS' AS producto#(lf)    UNION ALL#(lf)    SELECT #(lf)        
'CLA8' AS codigo_producto, 'Clarasol Sol Oft 15mL' AS producto#(lf)    UNION ALL#(lf)    SELECT #(lf)        
'DES3' AS codigo_producto, 'Deslorat Jarabe 60 mL' AS producto#(lf)    UNION ALL#(lf)    SELECT #(lf)        
'LAC7' AS codigo_producto, 'Lacrifort Sol Oft 15mL' AS producto#(lf)    UNION ALL#(lf)    SELECT #(lf)        
'NAS4' AS codigo_producto, 'Nas 0,1% Sol Nasal 15mL' AS producto#(lf)    UNION ALL#(lf)    SELECT #(lf)        
'OPA3' AS codigo_producto, 'Opat 0,1%  Solución' AS producto#(lf)    UNION ALL#(lf)    SELECT #(lf)        
'RIN3' AS codigo_producto, 'Rinomax Sol Nasal 15mL' AS producto#(lf)    UNION ALL#(lf)    SELECT #(lf)        
'TOB2' AS codigo_producto, 'Tobrasol Ung. Oft.' AS producto#(lf)    UNION ALL#(lf)    SELECT #(lf)        
'TOD6' AS codigo_producto, 'Todex Susp Oft 5mL' AS producto#(lf))
#(lf)SELECT #(lf)    p.codigo, #(lf)    p.cliente, #(lf)    
    CASE #(lf)       
        WHEN p.codigo_producto = 'API1' THEN 'API3'#(lf)       
        WHEN p.codigo_producto = 'CLA5' THEN 'CLA7'#(lf)        
        WHEN p.codigo_producto = 'CLA3' THEN 'CLA6'#(lf)        
        WHEN p.codigo_producto = 'CLA2' THEN 'CLA9'#(lf)        
        WHEN p.codigo_producto = 'CLA1' THEN 'CLA8'#(lf)        
        WHEN p.codigo_producto = 'DES4' THEN 'DES3'#(lf)        
        WHEN p.codigo_producto = 'LAC6' THEN 'LAC7'#(lf)        
        WHEN p.codigo_producto = 'NAS5' THEN 'NAS4'#(lf)        
        WHEN p.codigo_producto = 'OPA1' THEN 'OPA3'#(lf)        
        WHEN p.codigo_producto = 'RIN1' THEN 'RIN3'#(lf)        
        WHEN p.codigo_producto = 'TOB6' THEN 'TOB2'#(lf)        
        WHEN p.codigo_producto = 'TOD5' THEN 'TOD6'#(lf)        
        ELSE p.codigo_producto#(lf)    
        END AS codigo_producto,#(lf)    
    p.cantidad,#(lf)    
    p.precio,#(lf)    
    p.Subtotal,#(lf)    
    p.IMS,#(lf)    
    p.fecha,#(lf)    
    p.ST03010 as tipo_doc,#(lf)    
    p.factura,#(lf)    
    COALESCE(sc.producto, p.producto) AS producto#(lf)FROM [iScalaDB].[dbo].[powerBI] p#(lf)LEFT JOIN SKU_Correctos sc ON #(lf)    
    CASE #(lf)        
        WHEN p.codigo_producto = 'API1' THEN 'API3'#(lf)        
        WHEN p.codigo_producto = 'CLA5' THEN 'CLA7'#(lf)        
        WHEN p.codigo_producto = 'CLA3' THEN 'CLA6'#(lf)        
        WHEN p.codigo_producto = 'CLA2' THEN 'CLA9'#(lf)        
        WHEN p.codigo_producto = 'CLA1' THEN 'CLA8'#(lf)        
        WHEN p.codigo_producto = 'DES4' THEN 'DES3'#(lf)        
        WHEN p.codigo_producto = 'LAC6' THEN 'LAC7'#(lf)        
        WHEN p.codigo_producto = 'NAS5' THEN 'NAS4'#(lf)        
        WHEN p.codigo_producto = 'OPA1' THEN 'OPA3'#(lf)        
        WHEN p.codigo_producto = 'RIN1' THEN 'RIN3'#(lf)        
        WHEN p.codigo_producto = 'TOB6' THEN 'TOB2'#(lf)        
        WHEN p.codigo_producto = 'TOD5' THEN 'TOD6'#(lf)        
        ELSE p.codigo_producto#(lf)    
        END = sc.codigo_producto#(lf)WHERE #(lf)    
    p.fecha >= DATEADD(YEAR, -5, GETDATE()) AND #(lf)    
    p.codigo_cadena IS NOT NULL AND #(lf)    
    p.codigo NOT LIKE '%NE%' AND#(lf)    
    p.codigo NOT LIKE 'IN%' AND#(lf)    
    p.codigo NOT LIKE 'NO%' AND#(lf)    
    p.codigo NOT LIKE 'OD%' AND#(lf)    
    p.codigo NOT LIKE 'CO%' AND#(lf)    
    p.codigo NOT LIKE 'OT%' AND#(lf)    
    p.codigo <> '' AND#(lf)    
    p.codigo_producto NOT LIKE '%MM'#(lf)ORDER BY p.fecha DESC;#(lf)", CommandTimeout=#duration(0, 0, 10, 0)]),